from __future__ import annotations

from enum import StrEnum


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    RISK_CHECKED = "RISK_CHECKED"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    APPROVED = "APPROVED"
    QUOTED = "QUOTED"
    SIGNING = "SIGNING"
    SIGNED_NOT_BROADCASTED = "SIGNED_NOT_BROADCASTED"
    BROADCASTED = "BROADCASTED"
    FILLED = "FILLED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    REJECTED_BY_USER = "REJECTED_BY_USER"


class ConditionalOrderStatus(StrEnum):
    ACTIVE = "ACTIVE"
    TRIGGERED = "TRIGGERED"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    EXECUTING = "EXECUTING"
    FILLED = "FILLED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    PAUSED = "PAUSED"

