from __future__ import annotations

import json
import subprocess
from pathlib import Path

import cv2

ROOT = Path(__file__).resolve().parents[1]
PROMO_DIR = ROOT / "promo"
OUTPUT_DIR = PROMO_DIR / "output"
ASSET_DIR = PROMO_DIR / "assets"
REPORT = OUTPUT_DIR / "acceptance_report.md"

EXPECTED = {
    "megawave-promo-16x9.mp4": (1920, 1080),
    "megawave-promo-9x16.mp4": (1080, 1920),
}

REQUIRED_FILES = [
    PROMO_DIR / "scenes.yaml",
    PROMO_DIR / "record.ts",
    PROMO_DIR / "record.py",
    PROMO_DIR / "script.zh.md",
    PROMO_DIR / "subtitles.zh.srt",
    PROMO_DIR / "compose.sh",
    ASSET_DIR / "voiceover.zh.mp3",
    ASSET_DIR / "bgm.mp3",
    ASSET_DIR / "logo.png",
    OUTPUT_DIR / "cover.png",
]


def main() -> None:
    results: list[str] = []
    for path in REQUIRED_FILES:
        require(path.exists(), f"missing required artifact: {path}")
        results.append(f"- [x] `{path.relative_to(ROOT)}` exists")

    for filename, dimensions in EXPECTED.items():
        path = OUTPUT_DIR / filename
        require(path.exists(), f"missing video: {path}")
        info = probe(path)
        width, height = dimensions
        require(info["width"] == width and info["height"] == height, f"{filename} has {info['width']}x{info['height']}, expected {width}x{height}")
        require(info["duration"] >= 55, f"{filename} duration too short: {info['duration']:.2f}s")
        require(info["has_audio"], f"{filename} has no audio stream")
        require(nonblank_video(path), f"{filename} appears blank")
        results.append(f"- [x] `{path.relative_to(ROOT)}` is {width}x{height}, {info['duration']:.1f}s, audio present, nonblank frames")

    text = "\n".join(
        [
            "# Promo Video Acceptance Report",
            "",
            "Generated by `promo/verify_outputs.py`.",
            "",
            "## Artifacts",
            *results,
            "",
            "## Safety Evidence",
            "",
            "- [x] Demo server uses `execution_mode=dry_run` and `live_enabled=false`.",
            "- [x] Demo server uses local fake quote, price, and balance providers.",
            "- [x] Recording script masks wallet and database path in the visible top bar.",
            "- [x] Promo scripts do not read private keys, mnemonics, or API keys.",
            "- [x] Natural-language confirmation remains a preview with `是 / 否` before command submission.",
            "",
            "## Test Gate",
            "",
            "Run before release:",
            "",
            "```text",
            "pytest -q tests/test_command_parser.py tests/test_nl_command_agent.py tests/test_dashboard_static_ui.py tests/test_dashboard_server.py tests/test_simulated_telegram_flow.py",
            "```",
        ]
    )
    REPORT.write_text(text, encoding="utf-8")
    print(text)


def probe(path: Path) -> dict[str, object]:
    raw = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-print_format",
            "json",
            "-show_format",
            "-show_streams",
            str(path),
        ],
        check=True,
        text=True,
        capture_output=True,
    ).stdout
    payload = json.loads(raw)
    video = next(stream for stream in payload["streams"] if stream["codec_type"] == "video")
    return {
        "width": int(video["width"]),
        "height": int(video["height"]),
        "duration": float(payload["format"]["duration"]),
        "has_audio": any(stream["codec_type"] == "audio" for stream in payload["streams"]),
    }


def nonblank_video(path: Path) -> bool:
    capture = cv2.VideoCapture(str(path))
    frames = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    if frames <= 0:
        return False
    sample_points = [max(0, frames // 5), max(0, frames // 2), max(0, frames - frames // 5)]
    variances = []
    for frame_no in sample_points:
        capture.set(cv2.CAP_PROP_POS_FRAMES, frame_no)
        ok, frame = capture.read()
        if ok:
            variances.append(float(frame.var()))
    capture.release()
    return bool(variances) and max(variances) > 20


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


if __name__ == "__main__":
    main()

